# -*- coding: utf-8 -*-
"""
/***************************************************************************
 StratumRO
                                 A QGIS plugin
 Pipeline MLOps integrat pentru descarcarea, filtrarea si procesarea automata a datelor geospatiale (LiDAR si Raster) la nivel national, cu suport pentru selectie geometrica si coduri administrative SIRUTA.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-05
        copyright            : (C) 2026 by Lefter Patrick Andrei , GeoMateLINE
        email                : lefterpatrickandrei@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load StratumRO class from file StratumRO.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .stratum_ro import StratumRO
    return StratumRO(iface)
