# -*- coding: utf-8 -*-
"""
Logic Handler for StratumRO-QGIS Integration.
Extracts and parses Direct JSON responses from LLM Orchestrator (NVIDIA NIM / Llama 3.3 70B),
validates Stereo70 (EPSG:3844) coordinate payloads, and prepares QGIS layers.
"""

import json
import re

try:
    from qgis.core import QgsGeometry, QgsVectorLayer, QgsFeature
    QGIS_AVAILABLE = True
except ImportError:
    QGIS_AVAILABLE = False


def extract_json_from_llm(raw_text: str):
    """
    Extracts and parses the first valid JSON object from LLM response text,
    stripping markdown block headers (e.g. ```json ... ```) if present.

    :param raw_text: Raw string returned by LLM completion.
    :return: Parsed dict if valid JSON, otherwise None.
    """
    if not raw_text or not isinstance(raw_text, str):
        return None

    try:
        # Search for first JSON object enclosed in braces { ... }
        json_match = re.search(r'\{.*\}', raw_text, re.DOTALL)
        if json_match:
            clean_json = json_match.group(0)
            return json.loads(clean_json)
    except Exception:
        pass
    return None


class StratumOrchestrator:
    """
    Orchestrates segmentation plans generated by LLM for StratumRO QGIS plugin.
    """

    REQUIRED_KEYS = ["project_name", "crs", "geometry", "administrative"]

    def __init__(self, llm_payload: dict):
        """
        :param llm_payload: Parsed JSON dictionary from extract_json_from_llm.
        """
        self.data = llm_payload or {}

    def is_valid(self) -> bool:
        """Checks if payload contains all required fields."""
        if not isinstance(self.data, dict):
            return False
        return all(key in self.data for key in self.REQUIRED_KEYS)

    def validate_plan(self) -> bool:
        """Validates payload schema and coordinate reference system."""
        if not self.is_valid():
            return False
        
        crs = str(self.data.get("crs", "")).upper()
        # Accept Stereo70 variants: EPSG:3844 or EPSG:31700
        if "3844" not in crs and "31700" not in crs:
            return False
        return True

    def get_crs(self) -> str:
        return self.data.get("crs", "EPSG:3844")

    def get_siruta_code(self):
        admin = self.data.get("administrative", {})
        if isinstance(admin, dict):
            return admin.get("siruta_code")
        return None

    def get_geometry_wkt(self) -> str:
        """Converts GeoJSON geometry dict to WKT representation."""
        geom = self.data.get("geometry", {})
        if not isinstance(geom, dict):
            return ""

        g_type = geom.get("type", "").upper()
        coords = geom.get("coordinates", [])

        if g_type == "POLYGON" and coords:
            ring = coords[0]
            pt_strs = [f"{pt[0]} {pt[1]}" for pt in ring if len(pt) >= 2]
            return f"POLYGON(({', '.join(pt_strs)}))"
        elif g_type == "POINT" and coords:
            return f"POINT({coords[0]} {coords[1]})"

        return ""

    def to_qgis_geometry(self):
        """Converts payload geometry to QgsGeometry if QGIS libraries are present."""
        if not QGIS_AVAILABLE:
            return None
        wkt = self.get_geometry_wkt()
        if wkt:
            return QgsGeometry.fromWkt(wkt)
        return None

    def notify_ui_ready(self) -> bool:
        """Notification flag for QGIS UI update."""
        return self.validate_plan()
